feat: add log alias

diff --git a/bash/bin/leet b/bash/bin/leet
--- a/bash/bin/leet
+++ b/bash/bin/leet
@@ -23,11 +23,11 @@ function leet() {
     local -r problem_name="$1"
 
     mkdir "${problem_name}"
-    cd "${problem_name}" || exit
+    cd "${problem_name}" || return
     touch "${problem_name}.py" "${problem_name}_soln.py"
 
     placeholder "${problem_name}"
-    cd .. || exit
+    cd .. || return
 }
 
 function placeholder() {
@@ -51,14 +51,14 @@ EOF
 """
 EOF
 
-    echo "${placeholder_content}" >"${problem_name}.py"
-    echo -e "${empty_python_docstring}\n" >"${problem_name}_soln.py"
-    echo "${placeholder_content}" >>"${problem_name}_soln.py"
+    printf '%s\n' "${placeholder_content}" >"${problem_name}.py"
+    printf '%s\n' "${empty_python_docstring}\n" >"${problem_name}_soln.py"
+    printf '%s\n' "${placeholder_content}" >>"${problem_name}_soln.py"
 }
 
 function usage() {
     echo
-    echo "Usage: At least one argument required"
+    printf '%s\n' "Usage: At least one argument required"
 }
 
 main "$@"
diff --git a/bash/bin/readmee b/bash/bin/readmee
--- a/bash/bin/readmee
+++ b/bash/bin/readmee
@@ -18,26 +18,26 @@ function main() {
     if [[ $# -eq 1 && "$1" == "init" ]]; then
         if [[ ! -d markdown ]]; then
             mkdir markdown
-            cd markdown || exit
+            cd markdown || return
         fi
 
         init
     elif [[ -f main.md ]]; then
         generate_readme
     elif [[ -d markdown ]]; then
-        echo "dir: markdown/ found"
+        printf '%s\n' "dir: markdown/ found"
 
         if [[ -f markdown/main.md ]]; then
-            cd markdown || exit
-            echo "file: markdown/main.md found"
+            cd markdown || return
+            printf '%s\n' "file: markdown/main.md found"
 
             generate_readme
         else
-            echo "file: markdown/main.md not found"
+            printf '%s\n' "file: markdown/main.md not found"
             init
         fi
     else
-        echo "usage: type \`readme init\` to initialize a markdown directory"
+        printf '%s\n' "usage: type \`readme init\` to initialize a markdown directory"
     fi
 }
 
@@ -48,22 +48,22 @@ function generate_readme() {
     if [[ -f compiled.md ]]; then
         mv compiled.md ../README.md
 
-        echo "Succesfully compiled markdown and generated README"
+        log::success "compiled markdown and generated README"
     else
-        echo "error: compiling failed"
+        log::error "compiling failed"
     fi
 
-    cd || exit
+    cd || return
 }
 
 # Initialize markdown dir
 function init() {
-    echo "Initializing markdown directory..."
+    printf '%s\n' "Initializing markdown directory..."
 
     touch markdown/main.md
     mkdir markdown/sections
 
-    echo "Done"
+    printf '%s\n' "Done"
 }
 
 main "$@"
