wip: lint

diff --git a/bash/aliases/resume b/bash/aliases/resume
--- a/bash/aliases/resume
+++ b/bash/aliases/resume
@@ -1,9 +1,8 @@
 #! /bin/bash
 
 function resume() {
-    local input_path="$(extract_value_assoc "${_PATHS}" "downloads")/${_RESUME_FILE}"
-    local repo_path="$(extract_value_assoc "${_PATHS}" "repos")/seyLu.github.io"
-    local resume_path="${repo_path}/resume/${_RESUME_FILE}"
+    local -r input_path="$(extract_value_assoc "${_PATHS}" "downloads")/${_RESUME_FILE}"
+    local -r repo_path="$(extract_value_assoc "${_PATHS}" "repos")/seyLu.github.io"
 
     local commit_msg="feat (resume): "
     if [[ -z "$1" ]]; then
@@ -12,13 +11,20 @@ function resume() {
         commit_msg+="$1"
     fi
 
-    if [[ -f "$input_path" ]]; then
-        gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${resume_path}" "${input_path}"
+    if [[ -f "${input_path}" ]]; then
+        if [[ -d "${repo_path}" ]]; then
+            gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/ebook -dNOPAUSE -dQUIET -dBATCH -sOutputFile="${repo_path}" "${input_path}"
 
-        cd "${repo_path}"
-        g "${commit_msg}"
+            cd "${repo_path}" || exit
+            g "${commit_msg}"
 
-        rm "${input_path}"
+            rm "${input_path}"
+        else
+            echo
+            echo "${repo_path}"
+            echo -e "${RED}Error: Repo does not exist.${ENDCOLOR}"
+            echo
+        fi
     else
         echo
         echo "${input_path}"
